### ISSUE TITLE
Fatal error with latest Caxy/HtmlDiff

### ISSUE THREAD

**Issue by jkenn99** [mkalkbrenner/php-htmldiff#3]
`Fatal error: Call to a member function purify() on null in /app/vendor/caxy/php-htmldiff/lib/Caxy/HtmlDiff/AbstractDiff.php on line 421`

I'll create a PR.

**Comment by JuliaBayer** [comment]
Thank you for your comment and the pull request! To avoid multiple purifying I adapted the html setter functions.
